name: Hagot
version: ${project.version}
main: me.hakej.hagot.hagot.Hagot
api-version: 1.13
authors: [Hakej]
description: Hakej's first Minecraft Spigot mod
website: https://github.com/Hakej

commands:
  hg:
    description: Hagot shorter command prefix
    usage: /<command>
  hagot:
    description: Hagot longer command prefix
    usage: /<command>
